Init{name(Dante)
scan()
blocking(0)
A=1-2*(gamenbr%2)
radarright(2*A)
lockgun(1)
setaccel(5)
z=600
regcore(C)
regcustom(I,2,dtcrobot)
regcustom(C,3,k&gunrmn)
regcldrobot(D,4)
regdtccookie(G,5)
bodyleft(5*A)
regcustom(H,6,distrmn<11&bodyrmnª0)}
C{scan()}
D{E=bodyrmn
q=(900+bodyaim+cldbearing-gunaim)%360-180
F=q-gunrmn
if(cldenergy¤energy)
stop()
endif
k=1
gunright(q)
if(movingª0)
bodyright(E)
waitfor(bodyrmnª0&gunrmnª0)
gosub(H)
waitfor(gunrmnª0)
endif
gunleft(F)
waitfor(gunrmnª0)
k=0}
G{if(gunrmnª0&distrmn>26&distrmn<340)
b=bodyrmn
stop()
bodyright(b)
endif}
H{ahead(z)
z=-z
stop()
bodyright(90*A)
continue()
gunleft(90*A)}
I{max(7*(distrmn<19),13-scandist/15)
min(result,energy-1)
min(result,(dtcenergy+3)/4)
fire(result)
scan()}