Init{name(Glamour)
blocking(0)
regascan(j,9)
m=c¤r*c¤s+2*r¤c*r¤s+3*s¤c*s¤r
d=90
l=600
if(mª1)
lockgun(1)
blocking(1)
back(l)
bodyleft(d)
back(l)
regcore(g)
regdtcrobot(j,1)
o=1
elseif(mª2)
gunleft(9)
lockgun(1)
regcore(a)
else
lockall(1)
regcore(n)
endif}
g{gunleft(o)
if(gunaim%90ª0)
o=-o
endif
scan()}
a{gunright(l)
d=-d
back(d)}
j{scan()
fire(dtcrobot*(l-scandist)/60)}
n{bodyleft(7*dtcrobotª0)
getothers()
r=result
d=dtcrobot
i=scandist
ahead(((d*(dtcenergy<energy)*(r<3))+dtccookie)*i+5*d)
fire((d*7+(dtcmine*(i<20)))*(r<2)+(d*(l-i)/70)*(r>1))
waitfor(gunheatª0)
scan()
d=dtcrobot
i=scandist
fire((d*7+dtcmine*(i<20))*(r<2)+(d*(l-i)/70+dtccookie)*(r>1))}
dead{q=energy
c=c*.9-mª1*((q<1)-(q>0))
s=s*.9-mª2*((q<1)-(q>0))
r=r*.9-mª3*((q<1)-(q>0))
store(c)
store(s)
store(r)}